### ISSUE TITLE
Urban expansion factor

### ISSUE THREAD

**Issue by faph** [OpenHydrology/floodestimation#1]
Implement urban expansion factor for estimation QMED. Not sure how this works. What are input parameters?

**Comment by faph** [comment]
Great stuff the Kjeldsen 2010 paper. I wasn't previously aware that the growth curve itself gets adjusted with urbext. It seems that this paper updates the urban adjustment for all of the three QMED, L-CV and L-SKEW. So I have implemented all of this.

I don't mean to be difficult, but now pretty much the entire FEH statistical procedures have been rewritten by Thomas, I would really like to drop support for all of the old 1999 methods. Because none of this is compatible with the old methods.

The urban expansion is separate from this as it simply updates urbext2000. I have given all `...Analysis` objects an attribute `year` which defaults to the current year.

**Comment by neilnutt** [comment]
I think we need to be compliant with the [EA's flood estimation guidelines] (http://persona.uk.com/A21Ton/Core_dox/H/H13.pdf):

*"Recent research (Kjeldsen, 2010) has led to a revision of the urban adjustment procedures. The research recommends that the UAF is used only for the adjustment of QMED. Unlike in earlier methods, growth curves are to be adjusted using a new method that does not include UAF. You should use this new method for adjusting growth curves."*

Elsewhere the paper seems to get a glowing endorsement.  So yes it looks like if it is in Kjeldsen 2010 then we should be incorporating it/aiming to have it default even if it is different to other legacy commercially available flood analysis programs for windows which others use.  Note also that god, sorry, Kjeldsen also presented a different UAF based on BFIHOST rather than SPRHOST.

In terms of dropping support for superseded methods, I say of course we should be targeting the best current methods however we need to be able to maintain a consistent api over the years.   i.e. todays methods will be the superseded methods of the future.  We need to be able to offer users smooth transitions to the next new method and not force them to have 2 installations running in parallel.
